# Generated by Django 4.2.2 on 2023-06-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_author_alter_bookinstance_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('Maintenance', 'Maintenance'), ('On loan', 'On loan'), ('Available', 'Available'), ('Reserved', 'Reserved')], default='m', help_text='Book availability', max_length=15),
        ),
    ]
